// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartLine.Infrastructure.Data;

#nullable disable

namespace SmartLine.Infrastructure.Migrations
{
    [DbContext(typeof(SmartLineDbContext))]
    [Migration("20260716003957_SessaoNovoCampos")]
    partial class SessaoNovoCampos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartLine.Core.Entities.Global.CampoMaquina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaquinaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Unidade")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaquinaId");

                    b.ToTable("CamposMaquina");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Global.Maquina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Fabricante")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Global.MotivoParada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaquinaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaquinaId");

                    b.ToTable("MotivosParada");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Global.TipoMedicao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaquinaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaquinaId");

                    b.ToTable("TiposMedicao");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.LeituraExtra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampoMaquinaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CampoMaquinaId");

                    b.HasIndex("SessaoId");

                    b.ToTable("LeiturasExtra");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Linha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Linhas");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.MaquinaLinha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Critica")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LinhaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaquinaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("TipoColeta")
                        .HasColumnType("integer");

                    b.Property<decimal>("VelocidadeNominal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("LinhaId");

                    b.HasIndex("MaquinaId");

                    b.ToTable("MaquinasLinha");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Medicao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoMedicaoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SessaoId");

                    b.HasIndex("TipoMedicaoId");

                    b.ToTable("Medicoes");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Parada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MotivoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MotivoId");

                    b.HasIndex("SessaoId");

                    b.ToTable("Paradas");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Producao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("Refugo")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessaoId");

                    b.ToTable("Producoes");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Sessao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaquinaLinhaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PrevisaoTermino")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SobreVelocidade")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TipoColeta")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VelocidadeNominal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MaquinaLinhaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.SessaoCampo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampoMaquinaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampoMaquinaId");

                    b.HasIndex("SessaoId");

                    b.ToTable("SessoesCampo");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Global.CampoMaquina", b =>
                {
                    b.HasOne("SmartLine.Core.Entities.Global.Maquina", "Maquina")
                        .WithMany("CamposMaquina")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Global.MotivoParada", b =>
                {
                    b.HasOne("SmartLine.Core.Entities.Global.Maquina", "Maquina")
                        .WithMany("MotivosParada")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Global.TipoMedicao", b =>
                {
                    b.HasOne("SmartLine.Core.Entities.Global.Maquina", "Maquina")
                        .WithMany("TiposMedicao")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.LeituraExtra", b =>
                {
                    b.HasOne("SmartLine.Core.Entities.Global.CampoMaquina", "CampoMaquina")
                        .WithMany("LeiturasExtra")
                        .HasForeignKey("CampoMaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLine.Core.Entities.Tenant.Sessao", "Sessao")
                        .WithMany("LeiturasExtra")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampoMaquina");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Linha", b =>
                {
                    b.HasOne("SmartLine.Core.Entities.Tenant.Cliente", "Cliente")
                        .WithMany("Linhas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.MaquinaLinha", b =>
                {
                    b.HasOne("SmartLine.Core.Entities.Tenant.Linha", "Linha")
                        .WithMany("Maquinas")
                        .HasForeignKey("LinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLine.Core.Entities.Global.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linha");

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Medicao", b =>
                {
                    b.HasOne("SmartLine.Core.Entities.Tenant.Sessao", "Sessao")
                        .WithMany("Medicoes")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLine.Core.Entities.Global.TipoMedicao", "TipoMedicao")
                        .WithMany()
                        .HasForeignKey("TipoMedicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sessao");

                    b.Navigation("TipoMedicao");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Parada", b =>
                {
                    b.HasOne("SmartLine.Core.Entities.Global.MotivoParada", "Motivo")
                        .WithMany()
                        .HasForeignKey("MotivoId");

                    b.HasOne("SmartLine.Core.Entities.Tenant.Sessao", "Sessao")
                        .WithMany("Paradas")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motivo");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Producao", b =>
                {
                    b.HasOne("SmartLine.Core.Entities.Tenant.Sessao", "Sessao")
                        .WithMany("Producoes")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Sessao", b =>
                {
                    b.HasOne("SmartLine.Core.Entities.Tenant.MaquinaLinha", "MaquinaLinha")
                        .WithMany("Sessoes")
                        .HasForeignKey("MaquinaLinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLine.Core.Entities.Tenant.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaquinaLinha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.SessaoCampo", b =>
                {
                    b.HasOne("SmartLine.Core.Entities.Global.CampoMaquina", "CampoMaquina")
                        .WithMany("SessoesCampo")
                        .HasForeignKey("CampoMaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLine.Core.Entities.Tenant.Sessao", "Sessao")
                        .WithMany("SessoesCampo")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampoMaquina");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Usuario", b =>
                {
                    b.HasOne("SmartLine.Core.Entities.Tenant.Cliente", "Cliente")
                        .WithMany("Usuarios")
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Global.CampoMaquina", b =>
                {
                    b.Navigation("LeiturasExtra");

                    b.Navigation("SessoesCampo");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Global.Maquina", b =>
                {
                    b.Navigation("CamposMaquina");

                    b.Navigation("MotivosParada");

                    b.Navigation("TiposMedicao");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Cliente", b =>
                {
                    b.Navigation("Linhas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Linha", b =>
                {
                    b.Navigation("Maquinas");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.MaquinaLinha", b =>
                {
                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("SmartLine.Core.Entities.Tenant.Sessao", b =>
                {
                    b.Navigation("LeiturasExtra");

                    b.Navigation("Medicoes");

                    b.Navigation("Paradas");

                    b.Navigation("Producoes");

                    b.Navigation("SessoesCampo");
                });
#pragma warning restore 612, 618
        }
    }
}
